# -*- coding: utf-8 -*-
"""Despliegue_Clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlauvC9IcDgxbkQ8YcYuAeNbaaFcy7ib

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'
modelo, labelencoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))
#modelo

#Cargamos los datos futuros
#data = pd.read_csv("ataque_corazon-datosFuturos.csv")
#data.head()

#Interfaz gráfica

!pip install streamlit

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de riesgo de ataque al corazón (stroke)')

age = st.slider('Edad', min_value=0, max_value=100, value=30, step=1)
avg_glucose_level = st.number_input('Nivel promedio de glucosa', min_value=40.0, max_value=300.0, value=100.0, step=0.1)
hypertension = st.selectbox('Hipertensión', ['No', 'Yes'])
heart_disease = st.selectbox('Enfermedad cardíaca', ['No', 'Yes'])
ever_married = st.selectbox('Alguna vez casado/a', ['No', 'Yes'])
smoking_status = st.selectbox('Estado de fumador', ["'never smoked'", 'Unknown', "'formerly smoked'", 'smokes'])


#Dataframe
datos = [[age, avg_glucose_level, hypertension, heart_disease, ever_married, smoking_status]]
data = pd.DataFrame(datos, columns=['age','avg_glucose_level','hypertension','heart_disease','ever_married','smoking_status']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first se mantiene igual que en el entrenamiento
data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status'], drop_first=False, dtype=int) #3 o más categorías
data_preparada = pd.get_dummies(data_preparada, columns=['hypertension','heart_disease','ever_married'], drop_first=True, dtype=int) #2 categorías
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad/glucosa para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#El modelo final es Random Forest (basado en árboles), por lo tanto NO requiere normalización
#data_preparada[['age','avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age','avg_glucose_level']])
#data_preparada.head()

"""#**Predicciones**"""

#Hacemos la predicción con el Random Forest
Y_pred = modelo.predict(data_preparada)

#Se decodifica la predicción (estaba codificada 0/1 por el LabelEncoder)
Y_pred = labelencoder.inverse_transform(Y_pred)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de desempeño del modelo

st.warning("El modelo tiene un accuracy aproximado del 85% (validación cruzada)")
